server:
  port: 8080
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: catalogRoute
          uri: lb://catalog-service/
          predicates:
            - Path=/catalog/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    health-check:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true